### ISSUE TITLE
On mobile, the editor experience is completely broken

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#103]
- [ ] Typing a space leads to random characters being inserted in editor. 
- [ ] Additionally, need to optimise all views for mobile (landing page, curriculum view, learning interface)

**Comment by bhaskarSingh** [comment]
Using editor on mobile devices has been an inherent problem, for learning interface we can show a message like "thank you for showing interest in crypto PvZ smartpy development, our application includes coding challenges therefore if you intend to complete that portion, please head to your laptop/desktop computer browser to continue"

as for storyline and game view, it can be optimized for the mobile view but again optimization doesn't lead to any benefit since users will have to make a context switch for coding challenges, hence we can also show the same message as above.

**Comment by prastut** [comment]
@bhaskarSingh I see it's a problem with Monaco editor. Though the same problem is not present with Ace editor. Ace also has a diffing component.

**Comment by prastut** [comment]
Stale. On mobile, inform the user that the platform works better on desktop and capture emails to retarget those users again.
