### ISSUE TITLE
Unpredictable lighting in customizer

### ISSUE THREAD

**Issue by manangouhari** [buidl-labs/crypto-code-school-inside-tezos#172]
When you go to the customiser at `/tezos/claim-bot` - bot sometimes seems greyish, sometimes white-ish. I'm sure this has something to do with environment lighting.

![image](https://user-images.githubusercontent.com/31039184/108707684-68b04b80-7536-11eb-8c36-6e1338cc65f7.png)

@harsh242 or @bhaskarSingh please take a look.

**Comment by harsh242** [comment]
Yup, high chance that it could be due to lighting, because from what I recall initial colors are set to #ffffff 🤔

**Comment by prastut** [comment]
@manangouhari is this fixed? (It likely is, confirming)

**Comment by manangouhari** [comment]
> @manangouhari is this fixed? (It likely is, confirming)

It's not fixed yet.

**Comment by harsh242** [comment]
The reason why sometimes, we are facing with the greyish bot, is because we are using environmental lighting and the file size is too big i.e. 1.58 MB & may not be able to load sometimes 

Possible solutions:
1. Remove the environmental lighting and use our own lighting setup 
2. Compress the hdri file : [File Available here](https://github.com/buidl-labs/crypto-code-school-inside-tezos/blob/develop/static/royal_esplanade_1k.hdr)

@aayushsaini1 what do you suggest?

Cases: 
1. With 
`<Environment files="royal_esplanade_1k.hdr" />`
![image](https://user-images.githubusercontent.com/49694914/110910602-9586a000-8337-11eb-8ea6-d89705d9a6a3.png)

2. With environment bg set to true.
`<Environment background={true} files="royal_esplanade_1k.hdr" />`

3. Without Environment 
![image](https://user-images.githubusercontent.com/49694914/110910778-cebf1000-8337-11eb-9b60-991fcf9130d1.png)

**Comment by aayushsaini1** [comment]
Using HDRi w/o showing it is better as the above HDRi background is irrelevant.
But if we can compress our current HDRi, (which will ruin it's quality I guess), then we may be able to use it with visible background.

**Comment by harsh242** [comment]
Can you try compressing the file to the lowest? I have mentioned the file in the above comment.

**Comment by aayushsaini1** [comment]
file size is around 500kb.
[royal_esplanade_1k_compressed_50ppi.zip](https://github.com/buidl-labs/crypto-code-school-inside-tezos/files/6128689/royal_esplanade_1k_compressed_50ppi.zip)

Note: Compressing the HDRi also affects the lighting.

**Comment by harsh242** [comment]
Old File :

**Comment by harsh242** [comment]
Old File :
![image](https://user-images.githubusercontent.com/49694914/110917196-a5a27d80-833f-11eb-8ed0-b7d576e26da5.png)


New File 
![image](https://user-images.githubusercontent.com/49694914/110917079-83106480-833f-11eb-89b3-8e9a96f1e717.png)
