### ISSUE TITLE
Cryptobot Numbering to be regular numbers instead of random

### ISSUE THREAD

**Issue by harsh242** [buidl-labs/crypto-code-school-inside-tezos#235]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Cryptobot #[Number] should be regular numbers like #1,#2,#3, and so on, kind of like it was the first minted crypto bot instead of a random number which doesn’t make sense in a real-world scenario.

**Comment by prastut** [comment]
@bhaskarSingh let's discuss this when you are back.

**Comment by bhaskarSingh** [comment]
There's a technical reason behind it. It's to make sure to avoid a collision with token ids when in case two users try to mint a token at the same time.

**Comment by prastut** [comment]
Understood @bhaskarSingh though conceptually we will have an order basis what transaction got mined first on-chain. I think there is a timestamp attached to all transactions and we can get an ordering from there. 

We can use those details and show them on the frontend. Though if this is pretty complicated, we can push it for later launch and just hide the random hash on frontend for the time being since it serves no purpose for the user.

**Comment by bhaskarSingh** [comment]
> Understood @bhaskarSingh <https://github.com/bhaskarSingh> though
conceptually we will have an order basis what transaction got mined first
on-chain. I think there is a timestamp attached to all

Yes, this would be possible to implement.

**Comment by prastut** [comment]
Look at "hic et nunc" platform and see what's happening there.

**Comment by bhaskarSingh** [comment]
Now the contract itself handles the numbering of crypto bots.
