### ISSUE TITLE
Rigidity Issues

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#89]
- [ ]  mapping solution to custom validation logic for validating correct answers and showing appropriate error messages for errors/updating custom validation logic to handle custom data.

- [ ] <strike>creating a component for rendering chapters without editor i.e no action for users to perform.</strike>

- [ ] update local storage key for overriding new content changes
- [x] ignore comments while validating solution

**Comment by bhaskarSingh** [comment]
Increasing content width makes its ascetic, not appealing + the trade-off isn't much worth it i.e user users still have to scroll as it was previously
![Screenshot 2020-05-07 at 2 23 40 PM](https://user-images.githubusercontent.com/16613455/81275050-becb0580-906e-11ea-981f-df7ff598c7cd.png)
![Screenshot 2020-05-07 at 2 23 55 PM](https://user-images.githubusercontent.com/16613455/81275060-c25e8c80-906e-11ea-98ee-bad883dd447c.png)

**Comment by prastut** [comment]
@bhaskarSingh 

Not urgent, though FYI: 
We seem to have turned off autocomplete entirely. I remember that the issue was that the recommendations were problematic since autocomplete doesn't recognise SmartPy syntax.  

Here is an issue that describes possible solutions: 
https://github.com/Microsoft/monaco-editor/issues/128

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
